### ISSUE TITLE
Hardware Build

### ISSUE THREAD

**Issue by Tyrel-Parker** [adangert/SpyTag-Wifi-game#2]
I could possibly just be overlooking a file somewhere, but there aren't any pictures or lists or diagrams of the specific hardware you are using. Is there anyway to remedy this?

**Comment by adangert** [comment]
Hi there, the best schematics I have for this project can be found here: https://twitter.com/adangert/status/1091744447740690432

I'm planning in the near future to clean this up and make it easier for others to put together and play as well.

**Comment by Tyrel-Parker** [comment]
I understand. Between this and a few close up pictures of the board, I think could replicate it. Do you think you could get some good close up pictures posted? I could try to develop a how-to as I build it. 

Or do you have an ETA for cleaning this up?

**Comment by adangert** [comment]
Currently working on my PhD, so I probably won't have time to get around to it until this summer. The best photo of the device can be seen here: http://www.spytaggame.com/

**Comment by Tyrel-Parker** [comment]
Hopefully I can help you out and get something made before that. The black box is for the batteries I'm assuming? 2-AA?

**Comment by adangert** [comment]
2 AAA batteries actually, but anything that powers the esp8266 should work, i.e. 1.5 volts

**Comment by lkhaskjdhlkashd** [comment]
I too would like a tutorial on what components to use (what you used), how to build, configure and use this device. This is very cool!

How long do the batteries last?
